ThomasCalle/10-Things-To-Do-In-Toronto

- README.md
> Thomas calle patch 1

- test/testapicode.js
- test/testapipage.html
I created a new folder "test" to test APIs. 
Open the HTML file and check the console. You can see the data from the event website.
I found out that Eventbrite doesn't provide event search api anymore so I used an API from [SeatGeek](https://seatgeek.com/) instead.
I'll explain the details tomorrow.
> Testing APIs

- .gitignore
- assets/js/script.js
I created a script.js file which contains the idea of the flow. 
The flow is explain as comments ex) "// 1-1. Get data using DayJS" . 
Please let me know if you have any questions.
> Created initial JS file and added a flow as comments

- index.html
Basic match to our wireframe with no styling.  Links for jQuery, JQueryUI and TailwindCSS have been added.
> Created index.html outline

- assets/js/script.js
- index.html
- test/testapicode.js
I changed IDs of some elements so that my JS file works with the latest HTML. 
Still need to change some styles to make it look better
> Adjust elements IDs

- assets/css/style.css
- index.html
Still working on finding out what is overriding the size in CSS.  Have corrected 1 portion for menu items
> added sticky navbar to HRML via TailwindCSS

- assets/js/script.js
- index.html
I updated index.html and script.js. 
Let's check the conflicts in HTML together
> Updated index.html and script.js

- assets/js/script.js
Here are the updates:
1. I added a class to all event buttons (both new events and searched events): class name "event-btn"
2. I fixed a small issue: we could click out side of the buttons and it returned "null" data and it was shown in the list. Now only when a button is clicked, next action will be triggered. 
3. Information in each button is shown as follows: "<event category> event name @date&time"
**All modifications are only in the script.js file. (HTML and CSS were not modified)** 
Let me know if you have any questions!
> Added class to Buttons and fixed some small issues

- assets/css/style.css
- index.html
I've got the header bar fixed again to the right sticky spot, changed the background color, and changed the text color to match the rest of the style.
> Rkml header fix

- assets/css/style.css
- assets/js/script.js
- index.html
Previous header corrections did not merge successfully.
Changed button styling.
Declared colours in CSS as root variables 
Removed frame from around the map
> fixed the header again, and changed button styling

- assets/js/script.js
- index.html
Updated date/time format
Please ignore any updates on HTML and CSS
> Shohei mod btn

- assets/css/style.css
- index.html
- Container Avatar
-  Avatar 
- Avatar Inner
- H1 Colour 
- .Hero
- @Media Colour Scheme
- Mouse Cursor Pointer
> [HTML & CSS] Update

- assets/js/script.js
Added comments/mark-ups to script.js file. 
Nothing else (index.html, style.css) has been changed.
> Added comments to JS file

- assets/css/style.css
- assets/js/script.js
- index.html
Button added to sticky navbar, element ids added to html so we can alter it to match our upcoming gradient.
Script to make button work added to JS file.
Muted the previously screen read version in CSS file.
Thanks to Mark Alfano, fixed the CDN stylesheet for TailwindCSS that was causing the button not to work.
> Added dark/light mode to HTML

- assets/css/style.css
- index.html
Once I added the light/dark mode, the buttons no longer were visible.  Added a static background color so they will pop against any background.
> Fixed button background color

- assets/js/script.js
Changed the class name of the map section from "container" to "map-container" 
script.js line #202
> Added a new class (map-container) to Map section

- assets/css/style.css
- index.html
#HTML 
- removed duplicate header
- removed duplicated html code
- fixed id for light/dark
- fixed footer
- fixed body tag
#CSS
-started creation of light & dark css to pull gradients
> [HMTL/CSS] Fixed conflicts

- assets/js/script.js
I added an underline to the link and fixed the issue with the date/time indication in the Event Details section.
> Added underline and show 2 lines for date & time seperately

- assets/js/script.js
- index.html
Edited Flowbite component.  Moved into a function in javascript, then set it the function to call on <body> load
> [HTML/CSS] added comments & moved javascript

- assets/js/script.js
- index.html
> fixed html issues, fixed comments, removed extra code
